# Generated by Django 5.1.2 on 2024-11-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_user_balance'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingrecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.user'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.user'),
        ),
    ]
